title: GenBio ICML Workshop 2026
author:
  name: GenBio ICML Workshop 2026
  email: genbioworkshop@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  GenBio focuses on solving fundamental problems in biology
  through generative AI.

baseurl: "/2026"
url: "https://genbio-workshop.github.io"

# Customized links for main menu
header_menu:
#  - title:Call for papers
 #   url: call_for_papers
  Call for Papers:
  Organizers:
  Confirmed Spearkers:
  Schedule:
  Technical Committee:
  Previous Editions:

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  skin: dark
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    # twitter: jekyllrb
    # github:  jekyll
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
